# Generated by Django 4.1.4 on 2023-02-03 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0006_task_complete'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.CharField(choices=[('static/images/image1.jpg', 'Image 1'), ('static/images/image2.jpg', 'Image 2'), ('static/images/image3.jpg', 'Image 3'), ('static/images/image4.jpg', 'Image 4'), ('static/images/image5.jpg', 'Image 5')], max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
