# Generated by Django 4.1.4 on 2023-02-03 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_image',
            new_name='profile_picture',
        ),
    ]
