# Generated by Django 4.1.4 on 2023-02-08 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_remove_task_project_task_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectTasks',
        ),
    ]
